#include <napinputevent.h>

// RTTI Definitions
RTTI_BEGIN_BASE_CLASS(nap::InputEvent)
RTTI_END_CLASS

RTTI_BEGIN_BASE_CLASS(nap::KeyEvent)
RTTI_END_CLASS

RTTI_BEGIN_BASE_CLASS(nap::KeyPressEvent)
RTTI_END_CLASS

RTTI_BEGIN_BASE_CLASS(nap::KeyReleaseEvent)
RTTI_END_CLASS

RTTI_BEGIN_BASE_CLASS(nap::PointerEvent)
RTTI_END_CLASS

RTTI_BEGIN_BASE_CLASS(nap::PointerClickEvent)
RTTI_END_CLASS

RTTI_BEGIN_BASE_CLASS(nap::PointerPressEvent)
RTTI_END_CLASS

RTTI_BEGIN_BASE_CLASS(nap::PointerReleaseEvent)
RTTI_END_CLASS

RTTI_BEGIN_BASE_CLASS(nap::PointerDragEvent)
RTTI_END_CLASS

RTTI_BEGIN_BASE_CLASS(nap::PointerMoveEvent)
RTTI_END_CLASS