typedef struct VkInstance_T* VkInstance;
typedef struct VkDebugReportCallbackEXT_T* VkDebugReportCallbackEXT;
typedef struct VkPhysicalDevice_T* VkPhysicalDevice;
typedef struct VkDevice_T* VkDevice;
typedef struct VkSurfaceKHR_T* VkSurfaceKHR;
typedef struct VkSwapchainKHR_T* VkSwapchainKHR;
typedef struct VkRenderPass_T* VkRenderPass;
typedef struct VkBuffer_T* VkBuffer;
typedef struct VkDeviceMemory_T* VkDevicMemory;