#include <parameternumeric.h>

DEFINE_NUMERIC_PARAMETER(nap::ParameterFloat)
DEFINE_NUMERIC_PARAMETER(nap::ParameterDouble)
DEFINE_NUMERIC_PARAMETER(nap::ParameterLong)
DEFINE_NUMERIC_PARAMETER(nap::ParameterInt)
DEFINE_NUMERIC_PARAMETER(nap::ParameterChar)
DEFINE_NUMERIC_PARAMETER(nap::ParameterByte)

DEFINE_NUMERIC_PARAMETER(nap::ParameterVec2)
DEFINE_NUMERIC_PARAMETER(nap::ParameterIVec2)
DEFINE_NUMERIC_PARAMETER(nap::ParameterVec3)
DEFINE_NUMERIC_PARAMETER(nap::ParameterIVec3)

