#pragma once

// Local Includes
#include "websocketinterface.h"

// External Includes
#include <component.h>
#include <nap/signalslot.h>
#include <nap/resourceptr.h>

namespace nap
{
	// Forward Declares
	class WebSocketComponentInstance;

	/**
	 * web-socket component resource. 
	 * Forwards all events that are generated by the given interface (client / server) to the running application.
	 * Listen to the various signals on the nap::WebSocketComponentInstance to receive websocket events.
	 * The events are received on the main thread.
	 */
	class NAPAPI WebSocketComponent : public Component
	{
		RTTI_ENABLE(Component)
		DECLARE_COMPONENT(WebSocketComponent, WebSocketComponentInstance)
	public:
		nap::ResourcePtr<WebSocketInterface> mInterface;			///< Property: "Interface" the web-socket client or server this component listens to for events.
	};


	/**
	 * web-socket component instance.
	 * Forwards all events that are generated by the given interface (client / server) to the running application.
	 * Listen to the various signals to receive web-socket events in your application.
	 * The events are received on the main thread.
	 */
	class NAPAPI WebSocketComponentInstance : public ComponentInstance
	{
		RTTI_ENABLE(ComponentInstance)
	public:
		WebSocketComponentInstance(EntityInstance& entity, Component& resource) :
			ComponentInstance(entity, resource)									{ }

		virtual ~WebSocketComponentInstance();

		/**
		 * Initialize websocketcomponentInstance based on the websocketcomponent resource
		 * @param entityCreationParams when dynamically creating entities on initialization, add them to this this list.
		 * @param errorState should hold the error message when initialization fails
		 * @return if the websocketcomponentInstance is initialized successfully
		 */
		virtual bool init(utility::ErrorState& errorState) override;

		const WebSocketInterface& getInterface() const					{ return *mInterface; }

		WebSocketInterface& getInterface()								{ return *mInterface; }

		nap::Signal<const WebSocketConnectionOpenedEvent&> connectionOpened;
		nap::Signal<const WebSocketConnectionClosedEvent&> connectionClosed;
		nap::Signal<const WebSocketConnectionFailedEvent&> connectionFailed;
		nap::Signal<const WebSocketMessageReceivedEvent&> messageReceived;

	private:
		WebSocketInterface* mInterface  = nullptr;
		WebSocketService* mService = nullptr;
	};
}
