# - Try to find NATIVEFILEDIALOG
# Once done this will define
# NATIVEFILEDIALOG_FOUND - System has NATIVEFILEDIALOG
# NATIVEFILEDIALOG_INCLUDE_DIRS - The NATIVEFILEDIALOG include directories
# NATIVEFILEDIALOG_LIBRARIES - The libraries needed to use NATIVEFILEDIALOG

find_path(NATIVEFILEDIALOG_DIR osx/include/nfd.h
HINTS
${THIRDPARTY_DIR}/nativefiledialog
${CMAKE_CURRENT_LIST_DIR}/../../thirdparty/nativefiledialog
)

if(WIN32)
    set(NATIVEFILEDIALOG_LIB_DIR ${NATIVEFILEDIALOG_DIR}/msvc/lib)
    set(NATIVEFILEDIALOG_INCLUDE_DIRS ${NATIVEFILEDIALOG_DIR}/msvc/include)
    set(NATIVEFILEDIALOG_LIBRARIES ${NATIVEFILEDIALOG_LIB_DIR}/nfd.lib)
    set(NATIVEFILEDIALOG_LIBRARIES_DEBUG ${NATIVEFILEDIALOG_LIB_DIR}/nfd.lib)
    set(NATIVEFILEDIALOG_IMPLIB_RELEASE ${NATIVEFILEDIALOG_LIB_DIR}/nfd.lib)
elseif(APPLE)
    set(NATIVEFILEDIALOG_LIB_DIR ${NATIVEFILEDIALOG_DIR}/osx/lib)
    set(NATIVEFILEDIALOG_INCLUDE_DIRS ${NATIVEFILEDIALOG_DIR}/osx/include)
    set(NATIVEFILEDIALOG_LIBRARIES ${NATIVEFILEDIALOG_LIB_DIR}/libnfd.a)
    set(NATIVEFILEDIALOG_LIBRARIES_DEBUG ${NATIVEFILEDIALOG_LIB_DIR}/libnfd.a)
    set(NATIVEFILEDIALOG_IMPLIB_RELEASE ${NATIVEFILEDIALOG_LIB_DIR}/libnfd.a) # have to add this here for the script to succeed..
else()
    # set(NATIVEFILEDIALOG_LIB_DIR ${NATIVEFILEDIALOG_DIR}/linux/lib)
    # set(NATIVEFILEDIALOG_INCLUDE_DIRS ${NATIVEFILEDIALOG_DIR}/linux/include)
    # set(NATIVEFILEDIALOG_LIBRARIES ${NATIVEFILEDIALOG_LIB_DIR}/libnativefiledialog.so)
    # set(NATIVEFILEDIALOG_LIBRARIES_DEBUG ${NATIVEFILEDIALOG_LIB_DIR}/libnativefiledialog.so)
    # set(NATIVEFILEDIALOG_IMPLIB_RELEASE ${NATIVEFILEDIALOG_LIB_DIR}/libnativefiledialog.so) # have to add this here for the script to succeed..
endif()


include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(nativefiledialog DEFAULT_MSG NATIVEFILEDIALOG_LIBRARIES NATIVEFILEDIALOG_IMPLIB_RELEASE NATIVEFILEDIALOG_INCLUDE_DIRS)

add_library(nativefiledialog STATIC IMPORTED)
set_target_properties(nativefiledialog PROPERTIES
                      IMPORTED_CONFIGURATIONS "Debug;Release;MinSizeRel;RelWithDebInfo"
                      IMPORTED_LOCATION_RELEASE ${NATIVEFILEDIALOG_LIBRARIES}
                      IMPORTED_LOCATION_DEBUG ${NATIVEFILEDIALOG_LIBRARIES_DEBUG}
                      IMPORTED_LOCATION_MINSIZEREL ${NATIVEFILEDIALOG_LIBRARIES}
                      IMPORTED_LOCATION_RELWITHDEBINFO ${NATIVEFILEDIALOG_LIBRARIES}
                      )
